export * from './role';
export * from './user';
export * from './journal';
export * from './status';
export * from './test';
export * from './actiondetail';
export * from './assessment';
export * from './department';
export * from './expertise';
export * from './review';
export * from './major'